### ISSUE TITLE
response.data is different types depending on URL requested

### ISSUE THREAD

**Issue by eseidel** [llfbandit/dio_cache_interceptor#21]
I'm not sure if this is expected or not.  It makes it hard to use this cache with the stream option since callers have to check the type.

```
PS C:\Users\micro\Documents\GitHub\flutter_eng_cycle_times> dart run .\bin\bug.dart
Instance of 'ResponseBody'
Instance of 'ResponseBody'
{userId: 1, id: 1, title: delectus aut autem, completed: false}
Instance of '_GeneratedStreamImpl<List<int>>'
Instance of '_GeneratedStreamImpl<List<int>>'
```

```
I'm using the dart command from my flutter install:

[√] Flutter (Channel master, 2.3.0-2.0.pre.90, on Microsoft Windows [Version 10.0.19041.928], locale en-US)
    • Flutter version 2.3.0-2.0.pre.90 at C:\Users\micro\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f82dedd5b9 (2 days ago), 2021-05-10 15:22:50 -0700
    • Engine revision f5b97d0b23
    • Dart version 2.14.0 (build 2.14.0-74.0.dev)
```

```dart 
import 'package:dio/dio.dart';
import 'package:dio_cache_interceptor/dio_cache_interceptor.dart';
import 'package:dio_cache_interceptor/src/store/file_cache_store.dart';

void main() async {
  final cacheOptions = CacheOptions(
    store: FileCacheStore('cache'),
    policy: CachePolicy.request,
    hitCacheOnErrorExcept: [401, 403],
    maxStale: const Duration(days: 7),
    priority: CachePriority.normal,
    cipher: null,
    keyBuilder: CacheOptions.defaultCacheKeyBuilder,
    // Default. Allows to cache POST requests.
    // Overriding [keyBuilder] is strongly recommended.
    allowPostMethod: false,
  );

  final nonCachingDio = Dio();

  final cachingDio = Dio()
    ..interceptors.add(DioCacheInterceptor(options: cacheOptions));

  var requestOptions = Options(
      // method: request.method,
      // headers: request.headers,
      responseType: ResponseType.stream);

  var url = 'https://jsonplaceholder.typicode.com/todos/1';
  var response = await nonCachingDio.request(url, options: requestOptions);
  print(response.data);
  response = await nonCachingDio.request(url, options: requestOptions);
  print(response.data);

  // Force refresh
  response = await cachingDio.request(url,
      options: cacheOptions.copyWith(policy: CachePolicy.refresh).toOptions());
  response = await cachingDio.request(url, options: requestOptions);
  print(response.data);
  response = await cachingDio.request(url, options: requestOptions);
  print(response.data);
}
```

**Comment by eseidel** [comment]
```
  dio:
    dependency: "direct main"
    description:
      name: dio
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.0.0"
  dio_cache_interceptor:
    dependency: "direct main"
    description:
      name: dio_cache_interceptor
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.3.1"
```
