### ISSUE TITLE
response.data is sometimes ResponseBody, breaking caching?

### ISSUE THREAD

**Issue by eseidel** [llfbandit/dio_cache_interceptor#22]
This is probably just a symptom from #21.  However this is how it's actually manifesting for me in my program (here reduced to a smaller test case).  Notice how the example url from #21 caches fine, however when I use a GitHub API URL caching blows up somewhere inside dio_cache_interceptor.  Maybe I've configured something wrong?

```
PS C:\Users\micro\Documents\GitHub\flutter_eng_cycle_times> rmdir .\cache\

Confirm
The item at C:\Users\micro\Documents\GitHub\flutter_eng_cycle_times\cache\ has children and the Recurse parameter was not specified. If you continue, all children will be 
 removed with the item. Are you sure you want to continue?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): A
PS C:\Users\micro\Documents\GitHub\flutter_eng_cycle_times> dart run .\bin\bug2.dart
Unhandled exception:
type 'ResponseBody' is not a subtype of type 'Stream<List<int>>' in type cast
#0      serializeContent (package:dio_cache_interceptor/src/util/content_serialization.dart:10:30)
#1      DioCacheInterceptor._buildCacheResponse (package:dio_cache_interceptor/src/dio_cache_interceptor.dart:213:13)
#2      DioCacheInterceptor.onResponse (package:dio_cache_interceptor/src/dio_cache_interceptor.dart:78:31)
#3      DioMixin.fetch._responseInterceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:526:28)
#4      DioMixin.checkIfNeedEnqueue (package:dio/src/dio_mixin.dart:795:22)
#5      DioMixin.fetch._responseInterceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart:524:22)
#6      new Future.<anonymous closure> (dart:async/future.dart:174:37)
#7      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#8      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
#9      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

```dart
import 'package:dio/dio.dart';
import 'package:dio_cache_interceptor/dio_cache_interceptor.dart';
import 'package:dio_cache_interceptor/src/store/file_cache_store.dart';

void main() async {
  final cacheOptions = CacheOptions(
    store: FileCacheStore('cache'),
    policy: CachePolicy.request,
    hitCacheOnErrorExcept: [401, 403],
    maxStale: const Duration(days: 7),
    priority: CachePriority.normal,
    cipher: null,
    keyBuilder: CacheOptions.defaultCacheKeyBuilder,
    // Default. Allows to cache POST requests.
    // Overriding [keyBuilder] is strongly recommended.
    allowPostMethod: false,
  );

  final cachingDio = Dio()
    ..interceptors.add(DioCacheInterceptor(options: cacheOptions));

  var cachableUrl = 'https://jsonplaceholder.typicode.com/todos/1';

  var options = Options(responseType: ResponseType.stream);

  var response = await cachingDio.request(cachableUrl, options: options);
  print(response.data.runtimeType);

  var errorUrl =
      'https://api.github.com/repos/flutter/flutter/compare/06e2fd63574bad2edafbe4653104ed76871ee0b1...d97f41caed971d4668ffe56699367ec3978db8f6';

  response = await cachingDio.request(errorUrl, options: options);
  print(response.data.runtimeType);
}
```

**Comment by eseidel** [comment]
```yaml
name: flutter_eng_cycle_times
publish-to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.17.3
dependencies: 
  dio: ^4.0.0
  github: ^8.1.0
  http: ^0.13.3
  dio_cache_interceptor: ^2.3.1
  stats: ^2.0.0
```

```
[√] Flutter (Channel master, 2.3.0-2.0.pre.90, on Microsoft Windows [Version 10.0.19041.928], locale en-US)
    • Flutter version 2.3.0-2.0.pre.90 at C:\Users\micro\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f82dedd5b9 (2 days ago), 2021-05-10 15:22:50 -0700
    • Engine revision f5b97d0b23
    • Dart version 2.14.0 (build 2.14.0-74.0.dev)
```

**Comment by eseidel** [comment]
```
  dio:
    dependency: "direct main"
    description:
      name: dio
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.0.0"
  dio_cache_interceptor:
    dependency: "direct main"
    description:
      name: dio_cache_interceptor
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.3.1"
```
